name: Build Windows ARM

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/*.md'
  pull_request:
    branches-ignore:
      - l10n_main

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - target: windows-arm64
            os: windows-11-arm
            project: src/Pixeval.Desktop/Pixeval.Desktop.csproj
            runtime: win-arm64
            command: publish
            output: artifacts/windows-arm64

    env:
      CONFIGURATION: Release
      MINVERBUILDMETADATA: build.${{ github.run_id }}.${{ github.run_attempt }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          filter: tree:0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Resolve package version
        id: package-version
        run: |
          $version = "5.0.0-ci.$env:GITHUB_RUN_NUMBER"
          "version=$version" >> $env:GITHUB_OUTPUT

      - name: Restore workload
        run: dotnet workload restore ${{ matrix.project }}

      - name: Restore files
        run: dotnet restore ${{ matrix.project }} -r ${{ matrix.runtime }} -p:Configuration=$env:CONFIGURATION

      - name: Publish
        if: ${{ matrix.command == 'publish' }}
        run: |
          dotnet publish ${{ matrix.project }} `
            -c $env:CONFIGURATION `
            -r ${{ matrix.runtime }} `
            --no-restore `
            -o ${{ matrix.output }}

      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Pixeval-${{ matrix.target }}
          path: ${{ matrix.output }}
          if-no-files-found: warn
          retention-days: 14
